"source /usr/share/vim/vim81/debian.vim
"source /usr/share/vim/vim81/defaults.vim

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab

syntax on
set mouse=
set ttymouse=
